// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/pokemon_stock_pair/get_pokemon_stock_pair_response.proto

package pokemon_stock_pair

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "pokestocks/proto/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPokemonStockPairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*common.PokemonStockPair `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetPokemonStockPairResponse) Reset() {
	*x = GetPokemonStockPairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPokemonStockPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonStockPairResponse) ProtoMessage() {}

func (x *GetPokemonStockPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonStockPairResponse.ProtoReflect.Descriptor instead.
func (*GetPokemonStockPairResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_rawDescGZIP(), []int{0}
}

func (x *GetPokemonStockPairResponse) GetData() []*common.PokemonStockPair {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto protoreflect.FileDescriptor

var file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_rawDesc = []byte{
	0x0a, 0x3e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x70,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x61, 0x69,
	0x72, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f,
	0x70, 0x61, 0x69, 0x72, 0x1a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x5f, 0x70, 0x61, 0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x1b, 0x47,
	0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x61,
	0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x61,
	0x69, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x25, 0x5a, 0x23, 0x70, 0x6f, 0x6b, 0x65,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_rawDescOnce sync.Once
	file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_rawDescData = file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_rawDesc
)

func file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_rawDescGZIP() []byte {
	file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_rawDescOnce.Do(func() {
		file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_rawDescData)
	})
	return file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_rawDescData
}

var file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_goTypes = []any{
	(*GetPokemonStockPairResponse)(nil), // 0: pokemon_stock_pair.GetPokemonStockPairResponse
	(*common.PokemonStockPair)(nil),     // 1: common.PokemonStockPair
}
var file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_depIdxs = []int32{
	1, // 0: pokemon_stock_pair.GetPokemonStockPairResponse.data:type_name -> common.PokemonStockPair
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_init() }
func file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_init() {
	if File_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetPokemonStockPairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_goTypes,
		DependencyIndexes: file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_depIdxs,
		MessageInfos:      file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_msgTypes,
	}.Build()
	File_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto = out.File
	file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_rawDesc = nil
	file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_goTypes = nil
	file_proto_pokemon_stock_pair_get_pokemon_stock_pair_response_proto_depIdxs = nil
}
