// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/pokemon_stock_pair/pokemon_stock_pair_service.proto

package pokemon_stock_pair

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PokemonStockPairService_GetAllPokemonStockPairs_FullMethodName = "/pokemon_stock_pair.PokemonStockPairService/GetAllPokemonStockPairs"
)

// PokemonStockPairServiceClient is the client API for PokemonStockPairService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PokemonStockPairServiceClient interface {
	GetAllPokemonStockPairs(ctx context.Context, in *GetAllPokemonStockPairsRequest, opts ...grpc.CallOption) (*GetAllPokemonStockPairsResponse, error)
}

type pokemonStockPairServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPokemonStockPairServiceClient(cc grpc.ClientConnInterface) PokemonStockPairServiceClient {
	return &pokemonStockPairServiceClient{cc}
}

func (c *pokemonStockPairServiceClient) GetAllPokemonStockPairs(ctx context.Context, in *GetAllPokemonStockPairsRequest, opts ...grpc.CallOption) (*GetAllPokemonStockPairsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllPokemonStockPairsResponse)
	err := c.cc.Invoke(ctx, PokemonStockPairService_GetAllPokemonStockPairs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokemonStockPairServiceServer is the server API for PokemonStockPairService service.
// All implementations must embed UnimplementedPokemonStockPairServiceServer
// for forward compatibility.
type PokemonStockPairServiceServer interface {
	GetAllPokemonStockPairs(context.Context, *GetAllPokemonStockPairsRequest) (*GetAllPokemonStockPairsResponse, error)
	mustEmbedUnimplementedPokemonStockPairServiceServer()
}

// UnimplementedPokemonStockPairServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPokemonStockPairServiceServer struct{}

func (UnimplementedPokemonStockPairServiceServer) GetAllPokemonStockPairs(context.Context, *GetAllPokemonStockPairsRequest) (*GetAllPokemonStockPairsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPokemonStockPairs not implemented")
}
func (UnimplementedPokemonStockPairServiceServer) mustEmbedUnimplementedPokemonStockPairServiceServer() {
}
func (UnimplementedPokemonStockPairServiceServer) testEmbeddedByValue() {}

// UnsafePokemonStockPairServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PokemonStockPairServiceServer will
// result in compilation errors.
type UnsafePokemonStockPairServiceServer interface {
	mustEmbedUnimplementedPokemonStockPairServiceServer()
}

func RegisterPokemonStockPairServiceServer(s grpc.ServiceRegistrar, srv PokemonStockPairServiceServer) {
	// If the following call pancis, it indicates UnimplementedPokemonStockPairServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PokemonStockPairService_ServiceDesc, srv)
}

func _PokemonStockPairService_GetAllPokemonStockPairs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPokemonStockPairsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokemonStockPairServiceServer).GetAllPokemonStockPairs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PokemonStockPairService_GetAllPokemonStockPairs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokemonStockPairServiceServer).GetAllPokemonStockPairs(ctx, req.(*GetAllPokemonStockPairsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PokemonStockPairService_ServiceDesc is the grpc.ServiceDesc for PokemonStockPairService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PokemonStockPairService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pokemon_stock_pair.PokemonStockPairService",
	HandlerType: (*PokemonStockPairServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllPokemonStockPairs",
			Handler:    _PokemonStockPairService_GetAllPokemonStockPairs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pokemon_stock_pair/pokemon_stock_pair_service.proto",
}
