// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: proto/pokemon_stock_pair/pokemon_stock_pair.proto

package pokemon_stock_pair

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "pokestocks/proto/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllPokemonStockPairsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllPokemonStockPairsRequest) Reset() {
	*x = GetAllPokemonStockPairsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPokemonStockPairsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPokemonStockPairsRequest) ProtoMessage() {}

func (x *GetAllPokemonStockPairsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPokemonStockPairsRequest.ProtoReflect.Descriptor instead.
func (*GetAllPokemonStockPairsRequest) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_rawDescGZIP(), []int{0}
}

type GetAllPokemonStockPairsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*common.PokemonStockPair `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllPokemonStockPairsResponse) Reset() {
	*x = GetAllPokemonStockPairsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPokemonStockPairsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPokemonStockPairsResponse) ProtoMessage() {}

func (x *GetAllPokemonStockPairsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPokemonStockPairsResponse.ProtoReflect.Descriptor instead.
func (*GetAllPokemonStockPairsResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllPokemonStockPairsResponse) GetData() []*common.PokemonStockPair {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_pokemon_stock_pair_pokemon_stock_pair_proto protoreflect.FileDescriptor

var file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_rawDesc = []byte{
	0x0a, 0x31, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f,
	0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x20, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x9e, 0x01, 0x0a, 0x17, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x69, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x82, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x69, 0x72, 0x73, 0x12, 0x32, 0x2e,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x61,
	0x69, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x33, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x25, 0x5a, 0x23, 0x70, 0x6f, 0x6b, 0x65, 0x73, 0x74,
	0x6f, 0x63, 0x6b, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_rawDescOnce sync.Once
	file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_rawDescData = file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_rawDesc
)

func file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_rawDescGZIP() []byte {
	file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_rawDescOnce.Do(func() {
		file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_rawDescData)
	})
	return file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_rawDescData
}

var file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_goTypes = []any{
	(*GetAllPokemonStockPairsRequest)(nil),  // 0: pokemon_stock_pair.GetAllPokemonStockPairsRequest
	(*GetAllPokemonStockPairsResponse)(nil), // 1: pokemon_stock_pair.GetAllPokemonStockPairsResponse
	(*common.PokemonStockPair)(nil),         // 2: common.PokemonStockPair
}
var file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_depIdxs = []int32{
	2, // 0: pokemon_stock_pair.GetAllPokemonStockPairsResponse.data:type_name -> common.PokemonStockPair
	0, // 1: pokemon_stock_pair.PokemonStockPairService.GetAllPokemonStockPairs:input_type -> pokemon_stock_pair.GetAllPokemonStockPairsRequest
	1, // 2: pokemon_stock_pair.PokemonStockPairService.GetAllPokemonStockPairs:output_type -> pokemon_stock_pair.GetAllPokemonStockPairsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_init() }
func file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_init() {
	if File_proto_pokemon_stock_pair_pokemon_stock_pair_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllPokemonStockPairsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllPokemonStockPairsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_goTypes,
		DependencyIndexes: file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_depIdxs,
		MessageInfos:      file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_msgTypes,
	}.Build()
	File_proto_pokemon_stock_pair_pokemon_stock_pair_proto = out.File
	file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_rawDesc = nil
	file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_goTypes = nil
	file_proto_pokemon_stock_pair_pokemon_stock_pair_proto_depIdxs = nil
}
